### ISSUE TITLE
Can't write to shared folder

### ISSUE THREAD

**Issue by jamesla** [wholebits/baseboxes#2]
I am unable to write files to the /vagrant mount however I can create folders and edit files. This works fine with other boxes.

Reproduction:
Create a ubuntu 17.04 box using this repo's basebox
`touch /vagrant/test`

You will get an permission error.

How can I make this work?

**Comment by wmoldwin** [comment]
Are you using the Parallels provider? This appears to be a compatibility issue affecting Parallels Tools 12.2 on Ubuntu 17.04. I don't know of anything that can be done about it other than wait and hope that Parallels provide a fix in a future update.

**Comment by jamesla** [comment]
I've actually just worked out that if you reinstall parallels tools on the box via the parallels menu and then reload the box the shared folder starts working correctly. Could it be something to do with the version of parallels tools that is put on this box when it is originally created?

**Comment by wmoldwin** [comment]
You are quite right. I was incorrectly still applying a patch intended for a previous version of Parallels Tools to this box. This has been corrected and updated boxes have been uploaded to Vagrant Cloud. Thanks for letting me know.

**Comment by jamesla** [comment]
Legend
